version: "3.9"

services:
  api: &api
    build:
      context: .
    hostname: api
    container_name: RINHA_API
    ports:
      - "8080:8080"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: "45MB"
          cpus: "0.35"
  api02:
    <<: *api 
    container_name: API_RINHA_2
    hostname: api02
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8082:8080"
 
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - api02
    ports:  
      - "9999:9999" 
    deploy:
      resources:
        limits:
          memory: "40MB"
          cpus: "0.25"
  db:
    container_name: RINHA_DB
    image: postgres
    hostname: db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./src/main/resources/ddl.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "420MB"
